CREATE TABLE purchase (
      id BIGINT AUTO_INCREMENT PRIMARY KEY,
      member_id BIGINT NOT NULL,
      total_price BIGINT NOT NULL,
      status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
      ordered_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      canceled_at DATETIME,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);