# ?? ? ?? ??
server:
  port: 8080

spring:
  application:
    name: dogdog

  # DB
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true


  flyway:
    enabled: false
# ?? ?? ??
logging:
  level:
    org.hibernate.SQL: DEBUG

